- country_explorer/country_explorer.html
- infowindow_custom/infowindow-custom.html
- overlayview/custommarker.html
- spreadsheets/mapwithsidebar.html
- styledmaps/wizard/index.html
> Updated samples to run on new GitHub home

- styledmaps/wizard/StyledMapWizard.js
- styledmaps/wizard/index.html
- Page views
- Setting a style of some kind
- Exporting to JSON or static map URL.
> Add analytics beacons.

- styledmaps/wizard/index.html
PTAL @stephenfarrar @stephenmcd
> Redirecting to new style wizard

- .travis.yml
- build/index.sh
- index.njk
- package.json
- serve.js
drops all non packaged samples and archive from html tree
> feat: improved index page

- rules/nunjucks.bzl
- rules/sample.bzl
- rules/strip_region_tags.bzl
> fix: remove region tags from jsfiddle js and html

- .github/workflows/master.yml
`git commit` exits with 1 if no changes
> build: do not fail if no change to dist

- rules/strip_region_tags.bzl
> fix: use correct sed command to strip lines with region tags

- .github/workflows/release.yml
- dist/BUILD.bazel
> build: add dist/BUILD.bazel back

- data.json
- dist/index.html
- dist/samples/deckgl-points/app.js
- dist/samples/deckgl-points/index.html
- dist/samples/deckgl-points/inline.html
- dist/samples/deckgl-points/jsfiddle.html
- dist/samples/deckgl-points/sample.html
- dist/samples/deckgl-points/style.css
- samples/deckgl-points/BUILD.bazel
- samples/deckgl-points/package.json
- samples/deckgl-points/src/index.js
- samples/deckgl-points/src/index.njk
- samples/deckgl-points/src/style.scss
- samples/samples.bzl
> feat: include deckgl earthquake sample

- index.njk
> fix: add title to iframe

- dist/index.html
- index.njk
> build: fix github pages

- README.md
- dist/samples/places-autocomplete/iframe.html
- dist/samples/places-autocomplete/index.html
- dist/samples/places-autocomplete/index.js
- dist/samples/places-autocomplete/inline.html
- dist/samples/places-autocomplete/jsfiddle.html
- dist/samples/places-autocomplete/jsfiddle.js
- dist/samples/places-autocomplete/sample.html
- samples/places-autocomplete/src/index.njk
- samples/places-autocomplete/src/index.ts
feat: add location bias selector
refactor: reset input with any form interaction
refactor: streamline infowindow and related field masks
docs: edit README
> fix: refactor places autocomplete sample

- dist/samples/add-map/iframe.html
- rules/sample.bzl
- rules/strip_region_tags.sh
- rules/strip_source_map_url.sh
> build: do not use sed in place editing

- data.json
- dist/index.html
- dist/samples/marker-accessibility/CLOUD_SHELL_INSTRUCTIONS.md
- dist/samples/marker-accessibility/iframe.html
- dist/samples/marker-accessibility/index.html
- dist/samples/marker-accessibility/index.js
- dist/samples/marker-accessibility/inline.html
- dist/samples/marker-accessibility/jsfiddle.html
- dist/samples/marker-accessibility/jsfiddle.js
- dist/samples/marker-accessibility/sample.html
- dist/samples/marker-accessibility/style.css
- samples/marker-accessibility/BUILD.bazel
- samples/marker-accessibility/package.json
- samples/marker-accessibility/src/index.njk
- samples/marker-accessibility/src/index.ts
- samples/marker-accessibility/src/style.scss
- samples/samples.bzl
This PR adds a new sample to demonstrate how to make markers accessible.
Fixes #637 🦕
> feat: adds a new marker accessibility sample

- .eslintrc.json
- samples/aerial-rotation/src/index.ts
- samples/layer-heatmap/src/index.ts
- samples/marker-animations-iteration/src/index.ts
- samples/marker-remove/src/index.ts
- samples/overlay-remove/src/index.ts
- samples/polyline-remove/src/index.ts
- samples/streetview-overlays/src/index.ts
> fix: export handlers used in html

- dist/samples/store-locator/iframe.html
- dist/samples/store-locator/index.html
- dist/samples/store-locator/index.js
- dist/samples/store-locator/inline.html
- dist/samples/store-locator/jsfiddle.js
- dist/samples/store-locator/style.css
- samples/store-locator/src/index.njk
- samples/store-locator/src/index.ts
- samples/store-locator/src/style.scss
Update sidebar flex direction to column so that search bar appears on top of result cards.
---
Fixes #567 🦕
> fix: improve store locator sample styling and fix undefined progress

- dist/samples/place-details/iframe.html
- dist/samples/place-details/index.html
- dist/samples/place-details/index.js
- dist/samples/place-details/inline.html
- dist/samples/place-details/jsfiddle.js
- samples/place-details/src/index.ts
> fix: build infowindow content without xss

- dist/samples/groundoverlay-simple/iframe.html
- dist/samples/groundoverlay-simple/index.html
- dist/samples/groundoverlay-simple/index.js
- dist/samples/groundoverlay-simple/inline.html
- dist/samples/groundoverlay-simple/jsfiddle.js
- dist/samples/overlay-remove/iframe.html
- dist/samples/overlay-remove/index.html
- dist/samples/overlay-remove/index.js
- dist/samples/overlay-remove/inline.html
- dist/samples/overlay-remove/jsfiddle.js
- samples/groundoverlay-simple/src/index.ts
- samples/overlay-remove/src/index.ts
> fix: newark overlay

- dist/samples/places-autocomplete-multiple-countries/iframe.html
- dist/samples/places-autocomplete-multiple-countries/index.html
- dist/samples/places-autocomplete-multiple-countries/index.js
- dist/samples/places-autocomplete-multiple-countries/inline.html
- dist/samples/places-autocomplete-multiple-countries/jsfiddle.js
- dist/samples/places-autocomplete/iframe.html
- dist/samples/places-autocomplete/index.html
- dist/samples/places-autocomplete/index.js
- dist/samples/places-autocomplete/inline.html
- dist/samples/places-autocomplete/jsfiddle.js
- samples/places-autocomplete-multiple-countries/src/index.ts
- samples/places-autocomplete/src/index.ts
> fix: remove origin from places autocomplete options

- dist/samples/places-autocomplete-multiple-countries/iframe.html
- dist/samples/places-autocomplete-multiple-countries/index.html
- dist/samples/places-autocomplete-multiple-countries/inline.html
- dist/samples/places-autocomplete-multiple-countries/style.css
- dist/samples/places-autocomplete/iframe.html
- dist/samples/places-autocomplete/index.html
- dist/samples/places-autocomplete/index.js
- dist/samples/places-autocomplete/inline.html
- dist/samples/places-autocomplete/jsfiddle.html
- dist/samples/places-autocomplete/jsfiddle.js
- dist/samples/places-autocomplete/sample.html
- dist/samples/places-autocomplete/style.css
- dist/samples/places-searchbox/iframe.html
- dist/samples/places-searchbox/index.html
- dist/samples/places-searchbox/inline.html
- dist/samples/places-searchbox/style.css
- samples/places-autocomplete/src/index.njk
- samples/places-autocomplete/src/index.ts
- shared/scss/_autocomplete.scss
> fix: add additional radio buttons for autocomplete type

- dist/samples/react-map/iframe.html
- dist/samples/react-map/index.html
- dist/samples/react-map/index.js
- package-lock.json
- package.json
- samples/react-map/BUILD.bazel
- samples/react-map/src/index.tsx
closes #946 
Not my favorite fix. 
TODO:
- create a type guard package for google maps
- create a deep-equals for google.maps (?)
- add custom hook to @googlemaps/react-wrapper
> fix: use custom hook with deep equals

- shared/webpack.config.js
> fix: webpack replace string in tsx

- dist/samples/webgl-deckgl/iframe.html
- dist/samples/webgl-deckgl/index.html
- dist/samples/webgl-deckgl/index.js
- dist/samples/webgl-deckgl/inline.html
- dist/samples/webgl-deckgl/jsfiddle.js
- dist/samples/webgl-overlay-simple/iframe.html
- dist/samples/webgl-overlay-simple/index.html
- package-lock.json
- package.json
- samples/webgl-deckgl/src/index.ts
Updates corresponding to https://developers.google.com/maps/documentation/javascript/releases#3.47.4
> fix: update webgl samples

- src/playground/google-maps-sample.ts
> fix: match developers.google.com styling

- package.json
See discussion in https://github.com/parcel-bundler/parcel/issues/5961#issuecomment-931544222.
> build: use PARCEL_WORKER_BACKED=process

- cloudbuild.yaml
closes #1024 
staged at https://storage.googleapis.com/geo-devrel-public-buckets/js-samples/b2b408e/samples/playground.html?sample=marker-simple
> fix: set content type to lowercase

- cloudbuild.yaml
- cors.json
closes #1034
Per object CORS is not currently enabled.
> fix: set cors headers

- sample-to-branch.sh
- shared/sandbox.config.json
> fix: add sandbox config

- dist/samples/user-editable-shapes/app/index.ts
- dist/samples/user-editable-shapes/docs/index.js
- dist/samples/user-editable-shapes/iframe/index.html
- dist/samples/user-editable-shapes/jsfiddle/demo.js
- dist/samples/user-editable-shapes/playground/index.ts
- samples/user-editable-shapes/index.ts
This adds event listeners to the sample.
> fix: add listeners to sample

- .github/workflows/push-to-gh-pages.yml
- README.md
- dist/index.html
- samples/index.html.njk
- samples/playground.html.njk
- tailwind.config.js
This adds an index page to list all samples and pushes to gh-pages.
closes #1196
> feat: add index page and push to gh-pages

- dist/samples/react-map/app/index.tsx
- dist/samples/react-map/docs/index.jsx
- dist/samples/react-map/iframe/index.html
- dist/samples/react-map/jsfiddle/demo.jsx
- dist/samples/react-map/playground/index.tsx
- samples/react-map/index.tsx
closes #1201
https://reactjs.org/link/switch-to-createroot
> fix: update to createRoot and render

- src/engines/typescript/sample.js
> fix: updates prettier to format quoteProps consistently

- samples/control-custom-state/index.ts
> Use semantic elements to improve a11y in control-custom-state sample.

- samples/infowindow-simple-max/index.ts
> Improve a11y in info window simple max example.

- samples/infowindow-simple/index.ts
> Improve a11y in info window simple example.

- samples/advanced-markers-html/index.ts
The element incorrectly used `content`; it should be `element`.
/update-dist
> fix: Fixes element

- samples/react-map/index.tsx
> fix: adds ts-ignore in react-map

- samples/infowindow-simple-max/index.ts
> Move ariaLabel to the correct InfoWindow* object

- samples/infowindow-simple/index.ts
> Move ariaLabel to the correct InfoWindow* object 

- src/_includes/layout.njk
Changes to only write one script tag for loading the JS API
> fix: updates dynamic_import conditional

- samples/advanced-markers-graphics/index.ts
> fix: Fix a typo in the "Use icon fonts" sample.

- samples/place-class/index.ts
- samples/place-class/place-class.json
- samples/place-text-search/place-text-search.json
Updates Place Class and Place Text Search examples for GA release.
- Moved place-class and place-text-search to weekly channel.
- Updated place-class to remove obsolete functions.
- Spiffed up place-class with an advanced marker, because put a marker on it!
Fixes #1661 🦕
> feat: Updates Place Class and Place Text Search examples for GA release.

- samples/custom-markers/custom-markers.json
- samples/custom-markers/index.ts
Updates the custom markers example to use advanced markers, and also migrates it to use the dynamic loader.
Fixes #1669 🦕
> feat: Updates custom markers example to use advanced markers.

- samples/event-click-latlng/event-click-latlng.json
- samples/event-click-latlng/index.ts
Updates lat/lng event demo to use dynamic loading for the event-click-latlng sample. That is all. 🦕
> refactor: Updates lat/lng event demo to use dynamic loading.

- samples/place-nearby-search/index.njk
- samples/place-nearby-search/index.ts
- samples/place-nearby-search/place-nearby-search.json
- samples/place-nearby-search/style.scss
This PR adds a new example map to support documentation for the upcoming Place Nearby Search feature. It also updates the Place Text Search example to use map.fitBounds(), for better behavior.
Fixes #1681  🦕
> feat: Adds example for Place v2 Nearby Search.

- samples/rgm-basic-map/index.tsx
feat: Adds example to demonstrate adding a map with React
> added missing region tag and license

- samples/rgm-basic-map/style.scss
feat: adding basic react map to samples
> Rgm basic map

- samples/rgm-basic-map/index.njk
- samples/rgm-basic-map/index.tsx
> fix: rgm sample work

- samples/web-components-map/index.njk
- samples/web-components-map/index.ts
- samples/web-components-map/style.scss
- samples/web-components-map/web-components-map.json
- samples/web-components-markers/index.ts
- samples/web-components-markers/web-components-markers.json
This change does the following things:
- Simplifies the "web components" examples to use direct loading, which greatly simplifies the map code for the easiest possible solution.
- Adds more region tags for doc demos.
hi 🦕
> fix: Updates wc map and marker examples to use direct loading.

- samples/advanced-markers-accessibility/index.ts
Adds some new region tags for docs, and adds scale attribute.
rawr 🦕
> docs: Adds region tags and scale attribute

- samples/rgm-autocomplete/index.njk
- samples/rgm-autocomplete/index.tsx
- samples/rgm-autocomplete/rgm-autocomplete.json
- samples/rgm-autocomplete/style.scss
- samples/rgm-basic-map/index.tsx
> fix: rgm ac example

- package-lock.json
- package.json
- samples/rgm-college-picker/index.njk
- samples/rgm-college-picker/index.tsx
- samples/rgm-college-picker/rgm-college-picker.json
- samples/rgm-college-picker/style.scss
- tsconfig.json
> feat: rgm college picker, mod res to bundler, dep on react-google-maps

- samples/rgm-college-picker/index.tsx
> fix: center map over us and ca

- samples/rgm-autocomplete/index.tsx
- samples/rgm-basic-map/index.tsx
- samples/rgm-college-picker/index.tsx
> fix: sol chan syntax

- samples/web-components-map/index.njk
- samples/web-components-markers/index.njk
> docs: Adds height style attribute to gmp-map element.

- samples/web-components-map/web-components-map.json
- samples/web-components-markers/web-components-markers.json
Adds missing libraries to wc examples.
hello 🦕
> fix: Adds missing library

- samples/streetview-overlays/index.ts
- samples/streetview-overlays/streetview-overlays.json
This change adds new links to the graphic files for the Streetview Overlay example.
Hi. 🦕
> fix: Updates markers to make sample functional again.

- samples/place-autocomplete-data-simple/index.ts
Possible malfunction due to bad region tag nesting (i hope)
---
> fix: moves region tag

- samples/place-autocomplete-data-simple/place-autocomplete-data-simple.json
> fix: changes version to weekly

- samples/place-autocomplete-data-session/place-autocomplete-data-session.json
- samples/place-autocomplete-data-simple/place-autocomplete-data-simple.json
> fix: fixes bad tags in config

- samples/place-autocomplete-data-simple/index.njk
> fix: Remove duplicate string value.

- samples/place-autocomplete-data-simple/index.ts
Removes some log lines from place-autocomplete-data-simple as they are no longer needed.
Fixes #1751  🦕
> fix: Removes log lines

- src/_includes/layout.njk
> fix: Update layout.njk

- samples/place-reviews/index.ts
Updated the TS file with Tom's review suggestions. 🦕 🦕 🦕 🦕 🦕
> fix: Update index.ts with reviewer comments
