googlemaps/js-samples

styledmaps/wizard/StyledMapWizard.js, styledmaps/wizard/index.html
This is necessary to prevent the following error:
`Mixed Content: The page at 'https://googlemaps.github.io/js-samples/styledmaps/wizard/index.html' was loaded over HTTPS, but requested an insecure script 'http://maps.google.com/maps/api/js?libraries=places&key=AIzaSyA4rAT0fdTZLNkJ5o0uaAwZ89vVPQpr_Kc'. This request has been blocked; the content must be served over HTTPS.`
There are other places that probably should be updated as well.
=> Use https so the wizard sample loads in modern browsers.

shared/context.njk, shared/layout.njk
it is incredibly difficult to use an environment variable here due to the Bazel sandbox
=> fix: hardcode key in templates

rules/nunjucks.bzl, rules/nunjucks.sh, rules/sample.bzl, shared/layout.njk
This simplifies the build to avoid modifiying and storing an intermediate data.json for each sample.
=> build: use mode on nunjucks macro

BUILD.bazel, README.md, dist/samples/deckgl-points/app.js, dist/samples/deckgl-points/inline.html, dist/samples/directions-complex/app.js, dist/samples/directions-complex/inline.html, dist/samples/directions-panel/app.js, dist/samples/directions-panel/inline.html, dist/samples/directions-simple/app.js, dist/samples/directions-simple/inline.html, dist/samples/event-poi/app.js, dist/samples/event-poi/inline.html, dist/samples/map-projection-simple/app.js, dist/samples/map-projection-simple/inline.html, dist/samples/maptype-image-overlay/app.js, dist/samples/maptype-image-overlay/inline.html, dist/samples/maptype-image/app.js, dist/samples/maptype-image/inline.html, dist/samples/places-queryprediction/app.js, dist/samples/places-queryprediction/inline.html, dist/samples/split-map-panes/app.js, dist/samples/split-map-panes/inline.html, dist/samples/streetview-custom-tiles/app.js, dist/samples/streetview-custom-tiles/inline.html, rollup.config.iframe.js, rules/sample.bzl, shared/layout.njk
This relaxes the transpilation for all develoment outputs, specifically the js that will be shown in the documentation and the jsfiddle. The iframe and index.html will still be using the js transpiled to support ie and less popular browsers.
=> feat: change babel options for inline sample output and jsfiddle js

dist/samples/marker-symbol-custom/iframe.html, dist/samples/marker-symbol-custom/index.html, dist/samples/marker-symbol-custom/index.js, dist/samples/marker-symbol-custom/inline.html, dist/samples/marker-symbol-custom/jsfiddle.js, samples/marker-symbol-custom/src/index.ts
This update changes the big yellow star to a more sensibly-sized blue pushpin icon. It also adds the anchor property, which ensures that the marker will stay in position at different zoom levels.
Fixes  #541 🦕
https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-custom
=> fix: replace yellow star with blue pushpin.

.bazelrc
This causes an error if no credentials are available. Ideally it would only warn like it does if 403.
=> build: disable remote cache by default

.bazelrc, dist/samples/marker-symbol-custom/iframe.html, dist/samples/marker-symbol-custom/index.html, dist/samples/marker-symbol-custom/index.js, dist/samples/marker-symbol-custom/inline.html, dist/samples/marker-symbol-custom/jsfiddle.js, samples/marker-symbol-custom/src/index.ts
fix: updates the icon for the Custom Symbols example, with a cleaner and more modern looking icon.
Fixes #563 🦕
=> fix: updates icon path and example description

dist/samples/control-custom/iframe.html, dist/samples/control-custom/index.html, dist/samples/control-custom/index.js, dist/samples/control-custom/inline.html, dist/samples/control-custom/jsfiddle.js, samples/control-custom/src/index.ts
This PR fixes a minor display issue with the control-custom sample (the button touches the top of the map). To fix this, I have added another style to the CSS.
Fixes #631
=> fix: add margin to top of custom control

dist/samples/places-autocomplete-addressform/iframe.html, dist/samples/places-autocomplete-addressform/index.html, dist/samples/places-autocomplete-addressform/inline.html, dist/samples/places-autocomplete-addressform/jsfiddle.html, dist/samples/places-autocomplete-addressform/sample.html, dist/samples/places-autocomplete-addressform/style.css, samples/places-autocomplete-addressform/src/index.njk, samples/places-autocomplete-addressform/src/style.scss
Address form margins caused inconsistent display in [sample documentation](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform), so removing the horizontally centered margins.
Also found during testing that it would be useful to have a "Clear form" button to try different addresses.
=> Adjust margins around autocomplete addressform

samples/marker-accessibility/src/index.ts, shared/package/package.json, shared/package/webpack.dev.js
fixes #645 by using a new version of dev-server bypassing https://github.com/webpack/webpack-dev-server/issues/2484
=> fix: use beta version of webpack dev server for globals

rules/sample.bzl
Add switch for using different key.
The new key can be set in .bazelrc.user similar to the .bazelrc file.
`build --action_env GOOGLE_MAPS_JS_SAMPLES_KEY_SPECIAL=AIza_some_special_key `
and then specify in the build file `YOUR_API_KEY="GOOGLE_MAPS_JS_SAMPLES_KEY_SPECIAL"`
The typical use case if for early access demos using `GOOGLE_MAPS_JS_SAMPLES_KEY_EAP`.
=> feat: add early access key pattern

dist/samples/directions-panel/iframe.html, dist/samples/directions-panel/index.html, dist/samples/directions-panel/index.js, dist/samples/directions-panel/inline.html, dist/samples/directions-panel/jsfiddle.js, samples/directions-panel/src/index.ts
The Directions Panel sample does not require any default map controls, and looks much better without them. This fix adds the  `disableDefaultUi: true` property, for a visually cleaner sample.
Fixes #727 🦕
=> fix: remove default controls from Directions sample

dist/samples/geocoding-component-restriction/iframe.html, dist/samples/geocoding-component-restriction/index.html, dist/samples/geocoding-component-restriction/index.js, dist/samples/geocoding-component-restriction/inline.html, dist/samples/geocoding-component-restriction/jsfiddle.html, dist/samples/geocoding-component-restriction/jsfiddle.js, dist/samples/geocoding-component-restriction/sample.html, samples/geocoding-component-restriction/src/index.njk, samples/geocoding-component-restriction/src/index.ts
This fix:
1. Adds an address to the Geocoding request, so that it works.
2. Changes `pre` to `code` to prevent DevSite elements from partially rendering in custom control.
Fixes #733 🦕
=> fix:adds address to example request, fixes weird button artifacts

dist/samples/infowindow-simple-max/iframe.html, dist/samples/infowindow-simple-max/index.html, dist/samples/infowindow-simple-max/index.js, dist/samples/infowindow-simple-max/inline.html, dist/samples/infowindow-simple-max/jsfiddle.js, dist/samples/infowindow-simple/iframe.html, dist/samples/infowindow-simple/index.html, dist/samples/infowindow-simple/index.js, dist/samples/infowindow-simple/inline.html, dist/samples/infowindow-simple/jsfiddle.js, samples/infowindow-simple-max/src/index.ts, samples/infowindow-simple/src/index.ts
fix:updates InfoWindow samples to show usage of `InfoWindowOpenOptions`.
Fixes #744 🦕
=> Infowindow options

.github/workflows/build.yml
skip the update dist step if tag based run
closes #730
=> build: skip updating dist for tags

dist/samples/store-locator/iframe.html, dist/samples/store-locator/index.html, dist/samples/store-locator/index.js, dist/samples/store-locator/inline.html, dist/samples/store-locator/jsfiddle.js, package-lock.json, package.json, samples/samples.bzl, samples/store-locator/BUILD.bazel, samples/store-locator/package.json, samples/store-locator/src/index.njk, samples/store-locator/src/index.ts, samples/store-locator/src/index.ts.orig, samples/store-locator/src/style.scss, samples/store-locator/stores.json
When user clicks on a marker or store name in the list view, zoom in on that location and switch the map view to a 45-degree tilt hybrid map. When the user zooms back out for any reason, revert to the original map type. If 45-degree imagery is not available at the chosen location, 0-degree tilt imagery is displayed.
Rebase on updated master from original PR #685
=> feat: store locator sample add 45-degree map view when viewing location details

dist/samples/marker-clustering/iframe.html, dist/samples/marker-clustering/index.html, dist/samples/marker-clustering/index.js, samples/marker-clustering/src/index.ts
> Both marker and marker clusters in this case can be navigated using arrow keys, however markers can only be keyboard focusable when they have click listeners registered on them.
=> fix: add click listener to make navigable by keyboard

e2e/samples/app.spec.ts
cleanup the app e2e tests and split the build step into a `beforeAll`
=> test: split into beforeAll

dist/samples/playground.html, samples/index.html.njk
tl;dr This hides the vertical scrollbar which should never be necessary.
The scrollbar doesn't happen on the standalone page because it does not have a fixed height. It only shows up when embedded in an iframe or similar. In this case, there is communication between the iframe and the parent window to automatically adjust the height. However, this is not instantaneous and leads to a flash of the vertical scrollbar.
=> fix: hide scrollbar

dist/samples/control-custom/app/index.ts, dist/samples/control-custom/docs/index.js, dist/samples/control-custom/iframe/index.html, dist/samples/control-custom/jsfiddle/demo.js, dist/samples/control-custom/playground/index.ts, samples/control-custom/index.ts
Updates the custom control sample to be keyboard-accessible, by rewriting to create the button element in native HTML.
Change-Id: I1904dae8db70088ed8ba65cd8f264eb58bdd3c65
Fixes https://github.com/googlemaps/js-samples/issues/1228 🦕
=> fix:Updates custom control sample to be keyboard-accessible.

dist/samples/advanced-markers-html/docs/index.js, samples/advanced-markers-html/index.ts
Externally visible here:
https://developers.google.com/maps/documentation/javascript/advanced-markers/html-markers
=> fix: Remove accidental comment as per https://issuetracker.google.com/258237573

samples/advanced-markers-collision/index.njk, samples/advanced-markers-collision/index.ts
Updates the marker collision demo dropdown menu to use normal language rather than the JSAPI enum value, so that the demo can be used across all platforms. This change removes a function that generates the menu, and hard-codes the menu items in HTML. One side effect is that it slightly simplifies the code.
Fixes #1545  🦕
=> feat: Updates marker collision demo

.github/workflows/e2e.yml, .github/workflows/test.yml
The test workflows are not running on community-contributed pull requests, since they're only configured to run on push (available to users with write permissions).
This pull request adds a trigger for tests to run on pull requests that target the `main` branch.
=> chore: run tests on pull requests

samples/place-autocomplete-element/index.ts, samples/place-autocomplete-map/index.ts
Updates instances of `pac.element` to `pac`. This is a breaking change for the preview release.
Fixes #1608  🦕
=> feat: Updates instances of pac.element to pac for AC preview.

samples/boundaries-text-search/index.ts, samples/place-autocomplete-element/index.ts, samples/place-autocomplete-map/index.ts
This PR adds `//@ts-ignore` comments to files for some pre-release example maps, for which certain lines were resulting in `test:jest` errors. These errors do NOT impact production content, this is done for the sake of preventing build errors of any kind.
Fixes #1624 🦕
=> fix: Adds ts-ignore comments for pre-release features

samples/web-components-events/index.njk, samples/web-components-events/index.ts, samples/web-components-events/style.scss, samples/web-components-events/web-components-events.json, samples/web-components-map/index.njk, samples/web-components-map/index.ts, samples/web-components-map/style.scss, samples/web-components-map/web-components-map.json, samples/web-components-markers/index.njk, samples/web-components-markers/index.ts, samples/web-components-markers/style.scss, samples/web-components-markers/web-components-markers.json
Adds three example maps for the [Web Components doc page](https://developers.google.com/maps/documentation/javascript/web-components/overview).
Fixes #1617  🦕
=> feat: Adds example maps for web components

samples/web-components-events/style.scss, samples/web-components-map/style.scss, samples/web-components-markers/style.scss
This will prevent subscrolling on the page, since example maps are set to 400px height by default.
=> fix: Change height style to 400px

samples/place-search/index.ts, samples/place-text-search/index.ts
This changes the "query" parameter to "textQuery" for the Place Search example.
=> fix: Changes "query" to "textQuery"

samples/place-autocomplete-element/place-autocomplete-element.json, samples/place-autocomplete-map/place-autocomplete-map.json
Updates "alpha" to "beta" in config for place-autocomplete-element, and place-autocomplete-map
Fixes #1665 🦕
=> fix: Changes alpha to beta for ac examples.

samples/place-autocomplete-map/style.scss
Adds a width attribute to gmp-place-autocomplete to prevent size changes on user input.
Fixes #1671  🦕
=> fix: Adds style attribute to prevent size changes

samples/web-components-markers/index.njk
Adds region tags for the inner gmp-map and gmp-marker components for a tutorial.
Fixes my need to always make things better. 🦕
=> fix: Adds region tags to index.njk

samples/advanced-markers-draggable/index.ts
This fix removes weird parenthesis from position values, which appear to have broken the infowindow functionality for this sample.
Fixes #<1688>🦕
=> fix: Fixes broken infowindow on event handler.

samples/place-nearby-search/index.ts
Minor improvements:
- Changes center value to use google.maps.LatLng; adds comment to clarify that we are restricting somewhere within the viewport of the map. I know declaring it twice seems a wee bit goofy, but adding that pus the comment will make the `maps_place_nearby_search_request` region make more sense.
- Changes example to use `DEMO_MAP_ID`.
- Updates demo coordinates to a location that will produce a more visually interesting outcome on the map.
Fixes no issue 🦕
=> fix: Updates sample to show a location with more visual interest.

samples/programmatic-load-button/index.ts
Investigation revealed that the static map API key has been set to "YOUR_API_KEY", rendering the live example somewhat useless. Since there's already code on the page to get an API  key, I restructured the call to get the key when the page loads, and pass that value to the static map so that it can actually load.
Fixes #1691 🦕
=> fix: Updates api key so static map can display

samples/place-nearby-search/index.ts, samples/place-text-search/index.ts
Problem: The example map uses a custom reduced-POI map ID. At one point a request was made to obscure the map ID parameter to avoid exposing the custom map ID. This is not ideal since the map ID parameter is required, and must be exposed. Visually users will not see the parameter, and that's a problem. The example works when users link to JS Fiddle using the buttons, but if the code is copied and pasted it won't work. 
Solution: Get rid of the custom map ID and use DEMO_MAP_ID; remove the exclude tag which hides the needed map ID parameter.
This change also adds a couple of type declarations that were missing for some reason.
This fix is in response to b/316906523 🦕
=> fix: Removes exclusion tags, changes to use DEMO_MAP_ID

samples/combining-data/index.ts, samples/earthquake-circles/index.ts, samples/layer-data-dynamic/index.ts, samples/layer-data-event/index.ts, samples/layer-data-quakes-red/index.ts, samples/layer-data-quakes/index.ts, samples/map-projection-simple/index.ts
At some point our internal tests began failing on TypeScript errors that were not previously flagged. In each case the issue was due to a missing type declaration. This change adds those missing type declarations; in some cases this required minor refactoring.
Fixes my sanity 🦕
=> fix: Adds missing type declarations

package-lock.json, package.json, samples/rgm-college-picker/index.tsx, samples/rgm-college-picker/rgm-college-picker.json
=> fix: ecl shimming

samples/rgm-college-picker/index.tsx, samples/rgm-college-picker/style.scss
=> fix: removed gmpx alias, added div slots

samples/rgm-college-picker/index.tsx
=> fix: clean up picker comments

samples/web-components-map/style.scss
This is because we moved the CSS to the HTML in a previous PR, and no longer need the default markup.
---
=> fix: Remove default style from SCSS

samples/web-components-map/web-components-map.json, samples/web-components-markers/web-components-markers.json, src/_includes/layout.njk
Maps created using custom HTML elements (aka Web Components) do not require the `callback` parameter. This change introduces a conditional to the template, so that if `callback` is omitted in the configuration file, nothing will appear in the bootstrap. Removes the `callback` parameter from the two affected example maps.
Rawr! 🦕
=> fix: Adds a conditional to the `callback` parameter

src/_includes/layout.njk
This change updates the comment in the layout template, which is visible to developers. It changes the word "callback" to "script", which helps us to avoid referencing a nonexistent callback for scenarios that don't use them.
---
=> fix:Changes comment in layout template

samples/place-autocomplete-data-session/index.njk, samples/place-autocomplete-data-session/index.ts, samples/place-autocomplete-data-session/place-autocomplete-data-session.json, samples/place-autocomplete-data-session/style.scss, samples/place-autocomplete-data-simple/index.njk, samples/place-autocomplete-data-simple/index.ts, samples/place-autocomplete-data-simple/place-autocomplete-data-simple.json, samples/place-autocomplete-data-simple/style.scss, web-components-accessibility/index.njk, web-components-accessibility/index.ts, web-components-accessibility/style.scss, web-components-accessibility/web-components-accessibility.json
This change adds two new example maps to demonstrate the Place Autocomplete Data API.
- place-autocomplete-data-simple: shows making a single request.
- place-autocomplete-data-session: shows a simple type-ahead integration with sessions.
Fixes #1744  🦕
=> feat: Adds new example maps to demonstrate the place autocomplete data API

samples/place-photos/style.scss
Adds box-sizing attribute to container, to prevent scrollbars on the DevSite page.
🦕🦕🦕
=> fix: Update style.scss

samples/place-reviews/index.ts
Changes the place ID to a place without the  word "crazy" in the title, as that could be possibly offensive to some.
---
=> fix: Update index.ts

samples/dds-region-viewer/index.njk, samples/dds-region-viewer/index.ts, samples/dds-region-viewer/style.scss
This fix updates the region viewer as follows:
- Informational text is now only displayed when a user clicks a boundary, not when a result is returned by autocomplete.
- Adds an option to filter the autocomplete by the selected feature type.
Fixes #1798  🦕
=> fix: Updates region viewer behavior for autocomplete

samples/advanced-markers-basic-style/index.ts
This change adds code to demonstrate substituting the default glyph with a text character, and adjusts the positions of the demo markers so it looks nice.
🦕🦕🦕
=> feat: Adds code to show using text in place of pin glyph

samples/marker-clustering/index.ts
The MarkerClusterer import was left out of all regions, causing some users to ask "whaaaat???". This change moves the vital import statement back into the region for the code example so everyone can see it and no, you are NOT crazy.
🦕🦕🦕🦕🦕🦕🦕🦕
=> fix: Update index.ts to include MarkerClusterer import in region

samples/place-class/index.ts
Just a simple small change to move the Place class declaration into the function that's using it, to avoid using the pattern of passing Place as a function parameter.
🦕 🦕 🦕 🦕 🦕 🦕 🦕
=> fix: Moves Place class declaration to avoid confusing pattern.
